app/database/models/client.py
import datetime
from peewee import Model, CharField, DateTimeField
from app.database.database import db


class Client(Model):
    name = CharField()
    email = CharField()
    created_at = DateTimeField(default=datetime.datetime.now)

    class Meta:
        database = db

app/__init__.py
from flask import Flask
from config import configure_all

app = Flask(__name__)

configure_all(app)

app.run(debug=True)

app/routes/clients.py
from flask import Blueprint, render_template, request
from app.database.models.client import Client

client_route = Blueprint('client', __name__)

@client_route.route("/")
def client_list():
    """listar os clientes"""
    clients = Client.select()
    return render_template("list_clients.html", clients=clients)

@client_route.route("/", methods=["POST"])
def insert_client():
    """inserir os dados do cliente"""
    data = request.json
    
    new_client = Client.create(
        name = data['name'], 
        email = data['email'])
    
    return render_template('item_client.html', client=new_client)

@client_route.route("/new")
def form_client():
    """formulario para cadastrar um cliente"""
    return render_template("form_client.html")

@client_route.route("/<int:client_id>")
def detail_client(client_id):
    """Exibir os detalhes do cliente""" 
    client = Client.get_by_id(client_id)
    return render_template("detail_client.html", client=client)

@client_route.route("/<int:client_id>/edit")
def form_edit_client(client_id):
    """formulario para editar um cliente"""
    client = Client.get_by_id(client_id)
    
    return render_template("form_client.html", client=client)

@client_route.route("/<int:client_id>/update", methods=["PUT"])
def update_client(client_id):
    """atualizar informações do cliente"""
    data = request.json
    
    client_edited = Client.get_by_id(client_id)
    client_edited.name = data['name']
    client_edited.email = data['email']
    client_edited.save()
            
    return render_template('item_client.html', client=client_edited)

@client_route.route("/<int:client_id>/delete", methods=["DELETE"])
def delete_client(client_id):
    """deletar informações do cliente"""
    client = Client.get_by_id(client_id)
    client.delete_instance()
    
   
    return {"deleted": "ok"}

app/routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route("/")
def home():
    return render_template("index.html")

app/templates/detail_client.html
<ul>
    <li>Id: {{client.id}}</li>
    <li>Nome: {{client.name}}</li>
    <li>E-mail: {{client.email}}</li>
</ul>

app/templates/form_client.html
<form class="c-form" 
      {%if client%}
        action="{{ url_for('client.update_client', client_id=client.id) }}" 
      {% else %}
        action="{{ url_for('client.insert_client') }}" 
      {% endif %}

      method="{%if client%}PUT{%else%}POST{%endif%}" 

      {%if client%}
        c-swap="#client-{{client.id}}"
      {%else%}
        c-append="#list-clients"
      {% endif %}
      
      c-reload-container="true">

      
      
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="name" {%if client%}value="{{client.name}}" {%endif%}>
    </div>

    <div class="mb-3">
        <label class="form-label">E-mail</label>
        <input type="email" class="form-control" name="email" {%if client%}value="{{client.email}}" {%endif%}>
      </div>
    
 
    <button type="submit" class="btn btn-primary">
      {%if client%}Salvar{%else%}Criar {%endif%}</button>
  </form>

app/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename="css/app.css")}}">
  </head>
  <body>

    <div class="container">
      <h1 class="text-center">Gestão Clientes</h1>
    
      <!--Formulario add cliente-->
      <div id="form-client" c-container="{{url_for("client.form_client")}}"></div>
    <hr>
      <!--Lista de clientes-->
      <h2>Lista de Clientes</h2>
      <div c-container="{{url_for("client.client_list")}}"></div>
    
    </div>      

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="show-client"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script src="{{url_for('static', filename="js/cru.js")}}"></script>
  </body>
</html>

app/templates/item_client.html
<tr id="client-{{client.id}}">
    <th scope="row">{{client.id}}</th>
    <td>{{client.name}}</td>
    <td>{{client.email}}</td>
    <td>
        <button class="btn btn-secondary" 
            c-get="{{url_for("client.detail_client", client_id=client.id)}}" 
            c-target="#show-client" 
            data-bs-toggle="modal" data-bs-target="#exampleModal">Ver</button>

        <button class="btn btn-primary" 
            c-get="{{url_for("client.form_edit_client", client_id=client.id)}}"
            c-target="#form-client">Editar</button>

        <button class="btn btn-danger" c-delete="{{url_for("client.delete_client", client_id=client.id)}}" c-remove-closest="tr">Deletar</button>
    </td>
</tr>

app/templates/list_clients.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">E-mail</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="list-clients">
        {% for client in clients %}
           {% include 'item_client.html'%}
        {% endfor %}
    </tbody>
  </table>